### ISSUE TITLE
Web Sever: Dropdown Display Error

### ISSUE THREAD

**Issue by wesleyhstratusadv** [stratusadv/robit#27]
- Alpine js error on group dropdown. This causes the dropdown not to open. Error message appears when clicking on dropdown that already failed.

<img width="487" alt="image" src="https://github.com/stratusadv/robit/assets/91751620/7a6097e0-173a-4544-aee8-7b0cc0502b05">

**Comment by nathanjstratusadv** [comment]
This could be an issue with the return value of the job method not being a string. Should put in validation for that or cancel out!

**Comment by nathanjstratusadv** [comment]
Problem was caused by servers running with out a key as the request handler did not check the proper amount of parameters.
